# Generated by Django 5.0.1 on 2024-02-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='ProductName', max_length=100)),
                ('product_description', models.TextField(default='Description')),
                ('product_price', models.IntegerField(default=0)),
                ('product_Brand', models.CharField(default='Paws', max_length=75)),
                ('product_picture', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
