# Generated by Django 5.0.1 on 2024-02-21 06:08

import autoslug.fields
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=12)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_name')),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('pm', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Brand',
            field=models.CharField(default='PawsIndia', max_length=75),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
